(function(window, document, undefined) {
    document.domain = 'joins.com';

    window.commentLanguage = {
        ko: {
            joins: '조인스',
            facebook: '페이스북',
            twitter: '트위터',
            placeholder: '로그인 후 이용 가능합니다. 의견 작성을 위해 원하시는 계정으로 로그인 해주십시오',
            placeholderMobile: '댓글을 입력해 주세요.',
            placeholderMobileUnLogin: '로그인 후 댓글을 남기실 수 있습니다. 가지고 계신 계정 아이콘을 위에서 선택해 주세요.',
            selectSnsHide: '로그인 계정 선택',
            totalCount: '전체댓글',
            totalCountPaging: '더보기',
            submitHide: '댓글쓰기',
            textareaTitle: '댓글 내용',
            btnSubmit: '등록',
            btnReport: '신고하기',
            btnDelete: '삭제',
            btnLogout: '로그아웃',
            btnReply: '답글달기',
            btnGood: '댓글 찬성하기',
            btnBad: '댓글 반대하기',
            btnMore: '더보기',
            messageLogin: '<strong>[알림]</strong> 소셜 로그인을 활용해 손쉽게 의견을 작성해보세요.',
            shareSNS: '동시등록',
            sortNew: '최근순',
            sortGood: '추천순',
            sortBad: '반대순',
            mobileHide: '댓글',
            commentList: '댓글보기',
            commentWrite: '댓글쓰기',
            pm: '오후',
            am: '오전',
            standard: '게시판 관리기준',
            errorLogin: '로그인 후 사용하세요.',
            errorLoginCmt: '로그인 후 댓글 작성이 가능합니다.\n\n조인스 및 소셜 계정을 이용한 로그인 후 의견을 작성해 주십시오.',
            errorEmptyContent: '내용을 입력하세요.',
            errorPast: '스팸 댓글 방지를 위해 복사와 붙여넣기는 차단 됩니다.',
            errorCopy: '스팸 댓글 방지를 위해 복사와 붙여넣기는 차단 됩니다.',
            errorDrag: '스팸 댓글 방지를 위해 복사와 붙여넣기는 차단 됩니다.',
            errorMaxlength: '자 이내로 입력하세요.',
            errorWrite: '스팸 댓글 도배 방지를 위해 60초 이내 연속으로 2회 이상 댓글 입력이 불가능 합니다. 자세한 사항은 고객센터에서 문의 바랍니다.',
            errorBadIp: '해당 아이피는 쓰기가 불가능 합니다.\n자세한 사항은 고객센타에서 문의 바랍니다.',
            errorBadUser: '님의 아이디는 관리자가 차단하여 현재 댓글 입력이 불가능 합니다.\n자세한 사항은 고객센타에서 문의 바랍니다.',
            errorBadWord: '를 제외하고 입력하시면 정상적으로 댓글 입력이 가능합니다.\n자세한 사항은 고객센터에서 문의 바랍니다.',
            remove: '삭제',
            deleteComment: '삭제되었습니다',
            removeMessageUser: '작성자에 의해 삭제된 댓글입니다.',
            removeMessageAdmin: '관리자에 의해 삭제된 댓글입니다.',
            success: '댓글이 등록되었습니다.',
            fail: '등록이 실패했습니다.\n다시 시도해 주세요.',
            voteMessage: '참여해주셔서 감사합니다.',
            reportMessage: '광고,욕설,비방등 관리기준 위반글을 운영자에게 신고합니다. 신고하시겠습니까?',
            reportTrue: '신고가 접수 되었습니다.',
            reportFail: '이미 처리되었습니다.',
            socialComment: '소셜댓글이란?',
            layerSocialComment: '<span class="icon"></span>회원님이 사용중인 <em>트위터, 페이스북, 카카오</em>로<br> 댓글을 작성할 수 있는 새로운 오픈 댓글 서비스입니다.',
            mobileCommentListHeadTotalCount: '댓글 총',
            numberUnit: '개',
            returnToArticle: '본문보기',
            gotoCommentList: '댓글 전체보기',
            isReporter: '기자',
            writeWithVoice: '음성인식'
        },
        en: {
            joins: 'Joins',
            facebook: 'Facebook',
            twitter: 'Twitter',
            placeholder: '로그인 후 이용 가능합니다. 의견 작성을 위해 원하시는 계정으로 로그인 해주십시오EN',
            placeholderMobile: '댓글을 입력해 주세요EN.',
            placeholderMobileUnLogin: '로그인 후 댓글을 남기실 수 있습니다. 가지고 계신 계정 아이콘을 위에서 선택해 주세요.EN',
            selectSnsHide: '로그인 계정 선택EN',
            totalCount: '전체댓글EN',
            totalCountPaging: '더보기',
            submitHide: '댓글쓰기EN',
            textareaTitle: '댓글 내용',
            btnSubmit: '등록EN',
            btnReport: '신고하기EN',
            btnDelete: '삭제EN',
            btnLogout: '로그아웃EN',
            btnReply: '답글달기EN',
            btnGood: '댓글 찬성하기EN',
            btnBad: '댓글 반대하기EN',
            btnMore: '더보기EN',
            messageLogin: '<strong>페이스북, 트위터</strong>로 간편하게 로그인하세요EN',
            shareSNS: '동시등록EN',
            sortNew: '최근순EN',
            sortGood: '추천순EN',
            sortBad: '반대순EN',
            mobileHide: '댓글EN',
            commentList: '댓글보기EN',
            commentWrite: '댓글쓰기EN',
            pm: 'PM',
            am: 'AM',
            standard: '게시판 관리기준EN',
            errorLogin: '로그인 후 사용하세요.EN',
            errorLoginCmt: '로그인 후 댓글 작성이 가능합니다.\n\n조인스 및 소셜 계정을 이용한 로그인 후 의견을 작성해 주십시오.',
            errorEmptyContent: '내용을 입력하세요.',
            errorPast: '스팸 댓글 방지를 위해 복사와 붙여넣기는 차단 됩니다.',
            errorCopy: '스팸 댓글 방지를 위해 복사와 붙여넣기는 차단 됩니다.',
            errorDrag: '스팸 댓글 방지를 위해 복사와 붙여넣기는 차단 됩니다.',
            errorMaxlength: '자 이내로 입력하세요.',
            errorWrite: '스팸 댓글 도배 방지를 위해 60초 이내 연속으로 2회 이상 댓글 입력이 불가능 합니다. 자세한 사항은 고객센터에서 문의 바랍니다.EN',
            errorBadIp: '해당 아이피는 쓰기가 불가능 합니다.\n자세한 사항은 고객센타에서 문의 바랍니다.EN',
            errorBadUser: '님의 아이디는 관리자가 차단하여 현재 댓글 입력이 불가능 합니다.\n자세한 사항은 고객센타에서 문의 바랍니다.EN',
            errorBadWord: '를 제외하고 입력하시면 정상적으로 댓글 입력이 가능합니다.\n자세한 사항은 고객센터에서 문의 바랍니다.EN',
            remove: '삭제',
            deleteComment: '삭제되었습니다.',
            //removeMessage: '삭제된 글입니다.',
            removeMessageUser: '작성자에 의해 삭제된 댓글입니다.EN',
            removeMessageAdmin: '관리자에 의해 삭제된 댓글입니다.EN',
            success: '댓글이 등록되었습니다.',
            fail: '등록이 실패했습니다.\n다시 시도해 주세요.',
            voteMessage: '참여해주셔서 감사합니다.EN',
            reportMessage: '광고,욕설,비방등 관리기준 위반글을 운영자에게 신고합니다. 신고하시겠습니까?EN',
            reportTrue: '신고가 접수 되었습니다.',
            reportFail: '이미 처리되었습니다.',
            socialComment: '소셜댓글이란?EN',
            layerSocialComment: '<span class="icon"></span>회원님이 사용중인 <em>트위터, 페이스북, 카카오</em>로<br> 댓글을 작성할 수 있는 새로운 오픈 댓글 서비스입니다.EN',
            mobileCommentListHeadTotalCount: '댓글 총EN',
            numberUnit: '개EN',
            returnToArticle: '본문보기EN',
            gotoCommentList: '댓글 전체보기EN',
            isReporter: '기자',
            writeWithVoice: '음성인식'
        }
    };
})(window, document);